Repository JupGo/jupgo-client, pull requests merged in 2023-02, with the labels that each got.

#9 [ 🗺 Map ] UI 완성 후 타이머기능까지 연결하기
  .eslintrc.json
  package.json
  public/manifest.json
  src/asset/icon/IcFlogging.svg
  src/asset/icon/IcJupgoLogo.svg
  src/asset/icon/IcPause.svg
  src/asset/icon/IcRunning.svg
  src/asset/icon/IcStop.svg
  src/asset/icon/index.ts
  src/components/common/Router.tsx
  src/components/map/JupgoButton.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/RunningControl.tsx
  src/components/map/index.ts
  src/lib/hooks/useCouter.tsx
  src/pages/Map.tsx
  src/recoil/atom.ts
  src/styles/style.d.ts
  src/styles/theme.ts
  src/types/flogging.ts
  src/utils/dateParse.ts
  yarn.lock
Labels: 🗺 Map, 🖥 Code Review

#2 [ 🗺 MAP ] 카카오 지도 연결하기
  .eslintrc.json
  .gitignore
  package.json
  public/index.html
  public/manifest.json
  src/asset/icon/IcFlogging.svg
  src/asset/icon/IcJupgoLogo.svg
  src/asset/icon/IcPause.svg
  src/asset/icon/IcRunning.svg
  src/asset/icon/IcStop.svg
  src/asset/icon/index.ts
  src/components/common/Router.tsx
  src/components/map/JupgoButton.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/RunningControl.tsx
  src/components/map/index.ts
  src/lib/hooks/useCouter.tsx
  src/pages/Map.tsx
  src/recoil/atom.ts
  src/styles/globalStyle.ts
  src/styles/style.d.ts
  src/styles/theme.ts
  src/types/flogging.ts
  src/types/map.ts
  src/utils/dateParse.ts
  yarn.lock
Labels: 🗺 Map

#13 [feat] 사진 인증 화면 구현
  src/asset/icon/IcAlbum.svg
  src/asset/icon/IcBackBtn.svg
  src/asset/icon/IcCamera.svg
  src/asset/icon/IcMainDefault.svg
  src/asset/icon/IcSubDefault.svg
  src/asset/icon/index.ts
  src/asset/image/subDefaultImg1.png
  src/asset/image/subDefaultImg2.png
  src/asset/image/subDefaultImg3.png
  src/asset/image/subDefaultImg4.png
  src/pages/Authentication.tsx
Labels: feat

#5 [feat] 나무가 없을 때 diary 뷰 완성
  public/BgTreeDiaryEmpty.png
  public/IcHome.png
  src/pages/TreeDiary.tsx
Labels: feat

#11 [feat] 내가 키우는 나무들 화면 구현
  public/BgTreeDiary.png
  public/IcNextPage.png
  public/IcTempTree.png
  src/pages/TreeDiaryExist.tsx
Labels: feat
